# Generated by Django 6.0.2 on 2026-02-05 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id_product',
        ),
    ]
