# Generated by Django 6.0.2 on 2026-02-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_id_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('bisa dijual', 'Bisa Dijual'), ('tidak bisa dijual', 'Tidak Bisa Dijual')], max_length=50, unique=True),
        ),
    ]
